server:
  port: 10003
spring:
  application:
    name: im-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.46.128:3306/auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wereiyou
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.46.128:8848
  redis:
    host: 192.168.46.128
    port: 6379
    database: 0
    password: wereiyou123
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: 192.168.46.128
    port: 5672
    username: guest
    password: guest
client:
  permit-all:
    paths: /auth/login,/auth/register